# Lobby UltraHC — serwer Paper za proxy Velocity.
# online-mode=false, bo autoryzacje robi proxy (modern forwarding).
server-port=30065
online-mode=false
motd=UltraHC Lobby
max-players=1000
view-distance=6
simulation-distance=6
spawn-protection=0
allow-nether=false
allow-end=false
enable-command-block=false
network-compression-threshold=256
# Nie ustawiaj tu proxy — sekret forwardingu idzie do config/paper-global.yml
